"""cambio restrincciones campos en User

Revision ID: 1db9c82aa227
Revises: d181853cde60
Create Date: 2023-02-23 13:16:03.073186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db9c82aa227'
down_revision = 'd181853cde60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('usertype', sa.VARCHAR(length=20), nullable=False),
    sa.Column('useremail', sa.VARCHAR(length=80), nullable=False),
    sa.Column('usercompany', sa.VARCHAR(length=80), nullable=True),
    sa.Column('userprofile', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), nullable=False),
    sa.Column('usage_count', sa.INTEGER(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('token', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('useremail'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
