"""campo token ampliado a 4096

Revision ID: 1ff232d725d7
Revises: c839dc13b54d
Create Date: 2023-10-06 09:13:27.731752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff232d725d7'
down_revision = 'c839dc13b54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('usertype', sa.VARCHAR(length=20), nullable=True),
    sa.Column('useremail', sa.VARCHAR(length=80), nullable=False),
    sa.Column('usercompany', sa.VARCHAR(length=80), nullable=True),
    sa.Column('userprofile', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), nullable=False),
    sa.Column('usage_count', sa.INTEGER(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('token', sa.VARCHAR(length=120), nullable=True),
    sa.Column('stripe_client_id', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_client_id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
