"""Añade campo company name

Revision ID: 56f8ef530fb4
Revises: 6c6ea3888968
Create Date: 2023-02-21 12:50:39.620760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f8ef530fb4'
down_revision = '6c6ea3888968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('usertype', sa.VARCHAR(length=20), nullable=False),
    sa.Column('useremail', sa.VARCHAR(length=80), nullable=False),
    sa.Column('usercompany', sa.VARCHAR(length=80), nullable=True),
    sa.Column('userprofile', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), nullable=False),
    sa.Column('usage_count', sa.INTEGER(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('useremail'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
