"""Añade campo stripe_client_id a tabla user

Revision ID: c839dc13b54d
Revises: 1db9c82aa227
Create Date: 2023-03-31 10:00:48.968778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c839dc13b54d'
down_revision = '1db9c82aa227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('usertype', sa.VARCHAR(length=20), nullable=True),
    sa.Column('useremail', sa.VARCHAR(length=80), nullable=False),
    sa.Column('usercompany', sa.VARCHAR(length=80), nullable=True),
    sa.Column('userprofile', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), nullable=False),
    sa.Column('usage_count', sa.INTEGER(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('token', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
