"""Añade campo token a tabla user

Revision ID: d181853cde60
Revises: 56f8ef530fb4
Create Date: 2023-02-22 11:06:06.607389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd181853cde60'
down_revision = '56f8ef530fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('usertype', sa.VARCHAR(length=20), nullable=False),
    sa.Column('useremail', sa.VARCHAR(length=80), nullable=False),
    sa.Column('usercompany', sa.VARCHAR(length=80), nullable=True),
    sa.Column('userprofile', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), nullable=False),
    sa.Column('usage_count', sa.INTEGER(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('useremail'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
